apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: gabdzo/${{ values.name }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental